artemis.live.host=localhost
artemis.live.port=61616
artemis.backup.host=localhost
artemis.backup.port=61617

spring.artemis.user=admin
spring.artemis.password=admin
spring.artemis.mode=native

app.queue.name=demo.queue
order.created.queue.name=order.created

app.client-id=overflow-consumer-service

# --- Datasource (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/orderflow
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
