artemis.live.host=localhost
artemis.live.port=61616
artemis.backup.host=localhost
artemis.backup.port=61617

spring.artemis.user=admin
spring.artemis.password=admin
spring.artemis.mode=native

app.queue.name=demo.queue
order.created.queue.name=order.created


app.producer.interval-ms=8000
